<Project Sdk="Microsoft.NET.Sdk">

	<!-- Import tModLoader mod properties -->
	<Import Project="..\tModLoader.targets" />

	<!-- General -->
	<PropertyGroup>
		
	</PropertyGroup>
	<ItemGroup>
	  <None Remove="Content\Dusts\SuperMagicFireDust.png" />
	  <None Remove="Content\Dusts\SuperMagicIceDust.png" />
	  <None Remove="Content\Items\Weapons\Ranged\CursedDagger.png" />
	  <None Remove="Content\Items\Weapons\Ranged\IchorJavelin.png" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="Content\Bosses\" />
	  <Folder Include="Content\Items\Material\" />
	</ItemGroup>

	<!-- References -->

</Project>