<Project Sdk="Tomat.Terraria.ModLoader.Sdk/2.1.1">
	<ItemGroup>
	  <AdditionalFiles Remove="Localization\en-US\Mods.CalamityVanilla.GameTitles.hjson" />
	</ItemGroup>
 
	<!-- References -->
	<ItemGroup>
	  <PackageReference Include="Krafs.Publicizer" Version="2.3.0">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	</ItemGroup>

	<ItemGroup>
		<Publicize Include="tModLoader;FNA;ReLogic" IncludeCompilerGeneratedMembers="false" IncludeVirtualMembers="false" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Properties\" />
	</ItemGroup>
</Project>